### PR TITLE
Add holefix example

### PR DESCRIPTION
**Pull request by javl**
This updates the readme to show a workaround to use holes in your shapes. [See the readme in my fork for the result.](https://github.com/javl/svg2mod/blob/master/README.md)

When merging, make sure you change the image URL to point to the image in the svg2mod/svg2mod repository instead.

### CODE REVIEW

**Comment by Sodium-Hydrogen** [comment]
This issue has been fixed in a [previous commit](https://github.com/svg2mod/svg2mod/commit/5a6b18bbf6b1413eadcb48db2ac72ab9b2d79c34). I was able to get around to testing it today and it seemed to be working with holes properly. If anything we should remove
```
... Sometimes this will render propery in KiCad, but sometimes not.
```
From the readme

**Comment by javl** [comment]
I made a rectangle and used the difference function (in Inkscape) to cut out a couple of letters:
image
Loading this into Kicad (0.0mm line width, just infill), this is the result:
image
image
Moving some of the points around I immediately get a 'self-intersecting polygons are not allowed', meaning they are already self intersecting. Moving the top right point all the way over to the bottom right seems to reveal the letters are connected to the outside for some reason?
image

**Comment by Sodium-Hydrogen** [comment]
The way this tool interprets the drawings from inkscape is by basically placing a pen down for each path and not picking it up until it has drawn everything in that path. So in the case of your test.svg where there are separate elements that you don't want connecting you should separate the paths by using something like `Path > Break Apart`. Once you've broken all elements apart into their own path then there won't be a connecting line. And if you want the drawing to have an open space like in the test file you uploaded then you need to convert all the strokes into their own separate paths.

If kicad finds a closed shape it will automatically fill it. If there is another closed shape inside of it then it will have an open area. 

Here is what I got when I ran `svg2mod -i test.svg` on the attached svg.

image
[test.svg.zip](https://github.com/svg2mod/svg2mod/files/4637817/test.svg.zip)

I hope this clears up some functionality of svg2mod

**Comment by Sodium-Hydrogen** [comment]
I'm going to close this for now because it has been fixed. Except in rare cases, #8 but I'll see if a fix can be made for that

**Pull request closed without merging**
